### ISSUE TITLE
durability

### ISSUE THREAD

**Issue by iYi** [Xruptor/LagBar#10]
Hello i dont know if this is the correct section to post this. Want to ask if it will be possible to have a durability % status shown in the addon frame aswell thx.
p.s sry for my english :)

**Comment by Xruptor** [comment]
Sorry for the delay.  You'd like durability shown where exactly?  It's already shown in the tiny little frame it comes with.  Unless you meant the Character Window?  Could you be a bit more specific? 😄

**Comment by Xruptor** [comment]
Closing since I never heard back.
