### ISSUE TITLE
Feature request: hide labels

### ISSUE THREAD

**Issue by Daniele-f** [Xruptor/LagBar#11]
Hi, 

Is it possible to add an option to hide the labels and just show the numbers?

**Comment by Xruptor** [comment]
I don't think I understand the request?  Right now you have a few options to display world ping or just home.  Its literally one letter per display.  Can you give me an example?

**Comment by Daniele-f** [comment]
Right now, the addon shows: “60 FPS”.
I want to see only the number “60” and drop the “ FPS”.
