### ISSUE TITLE
Feature Request: high ping alarm

### ISSUE THREAD

**Issue by marajango** [Xruptor/LagBar#13]
Especially playing hardcore it would be helpful if you could set a threshold that will trigger a sound to play when the threshold is reached, like when the addon detects a lag spike.

**Comment by Xruptor** [comment]
I'd have to see how to implement this.  It would be to be off by default as it would severely annoy people I think.  I also would have to figure out how often and when to ping?  Obviously if I set it at a number then every single time that number would be reached then it would alarm, which repeatedly would be super annoying.
