### ISSUE TITLE
Feature Request: Accessibility Options for Improved In-Game Visibility

### ISSUE THREAD

**Issue by Jaffrito** [Xruptor/LagBar#14]
Hello Xruptor!

I'm writing to express my appreciation for this fantastic addon.  It's already proving incredibly helpful in identifying network issues during gameplay.

As someone with significant vision limitations, I often struggle with in-game text visibility. Larger fonts, a dark background, and lighter text colors would make a world of difference for me.

Therefore, I'd like to request the future implementation of some accessibility options, specifically focusing on scalable UI to adjust text size. Even just this one feature would have a tremendous impact on my ability to enjoy the game fully.

Thank you for your time and consideration. I'm confident that by prioritizing accessibility, your addon will become even more valuable to a wider range of players.

Sincerely,
Jafrito

**Comment by Jaffrito** [comment]
I apologize for the hasty request.
I just noticed that there is already a function /lagbar scale #

It will help a lot!

**Comment by Xruptor** [comment]
> I apologize for the hasty request. I just noticed that there is already a function /lagbar scale #
> 
> It will help a lot!

Oh no problem at all! I'm glad you were able to find the option.  Please note it's also available in the in game addons settings menu for WOW, in case you didn't want to use text commands.

Let me know if you have any other ideas for adjustments to help your visual limitations.  I'm always open for suggestions on all my addons.
