### ISSUE TITLE
Option to unclamp from screen edge

### ISSUE THREAD

**Issue by hianick** [Xruptor/LagBar#15]
Minor request, but being able to have the display slightly clip the edge of the screen can allow for a slightly cleaner appearance. I don't remember how I changed it for this to work, but I'm pretty sure I just changed a 0.5 to a 0 somewhere. https://imgur.com/a/EieMkN1

**Comment by Xruptor** [comment]
> Actually, I just realized I changed line 216 in LagBar.lua to false. I don't think it'd be possible to lose it offscreen if you tried regardless.

Actually somehow folks have done it.  In those situations, I was forced to clamp it to screen as they didn't realize I had an option to reset the position.  😆 

I'll set a config if I can.  That should help you.
