### ISSUE TITLE
Option to remove login message

### ISSUE THREAD

**Issue by JBabbb** [Xruptor/LagBar#16]
Hello Xruptor,

Could we please have an option to turn off the "lagbar loaded text" upon login or reload? 
Not a big issue, just a bit of a QoL thing.

Thank you for this addon. It is awesome :)

**Comment by Xruptor** [comment]
Mmmm didn't think it was that much of an issue.  But I don't see why I can't add an option to disable it.  :)

**Comment by JBabbb** [comment]
Thank you dearly :)

**Comment by Xruptor** [comment]
> Thank you dearly :)

Sure thing :) Enjoy
