### ISSUE TITLE
[TODO] Localization Updates

### ISSUE THREAD

**Issue by Xruptor** [Xruptor/LagBar#18]
@nanjuekaien1
Hey there!  I'm hoping that whenever you have spare time that you can update the localization of a few remaining addons of mine.  I'd truly appreciate it!  There is absolutely no rush and please don't feel obligated to do them. :)  It would be nice to have but it not 100% important.

https://github.com/Xruptor/LagBar
https://github.com/Xruptor/xanBuffTimers
https://github.com/Xruptor/xanDebuffTimers
https://github.com/Xruptor/XanChat
https://github.com/Xruptor/xanEXP

Thanks again for everything you do!  💚

**Comment by nanjuekaien1** [comment]
I'll do it tomorrow.

**Comment by Xruptor** [comment]
> I'll do it tomorrow.

WOW! You didn't have to do it so quickly!  I truly appreciate you going in and adding the localization though.  Thank you so very much!  💚

**Comment by nanjuekaien1** [comment]
Please don't be sad, these plugins are rarely used in CN, as most of them use ELvui/NDui (Chinese authors)/AltzUI(Chinese authors)

**Comment by Xruptor** [comment]
> Please don't be sad, these plugins are rarely used in CN, as most of them use ELvui/NDui (Chinese authors)/AltzUI(Chinese authors)

No not sad at all.  I know they aren't used as much, even the english players.  Still it's nice to have and I do appreciate it!
