### ISSUE TITLE
Classic Support?

### ISSUE THREAD

**Issue by feydain** [Xruptor/LagBar#2]
Do you plan to support Classic or just Retail?

**Comment by Xruptor** [comment]
I plan to support both.  Problem is I haven't had a chance to return to WOW and update my addons.  Also I need to lookup how to migrate addons to Classic.  I think it's just a TOC update.

**Comment by addohm** [comment]
Not sure what he's on about, the addon works in classic.  Just have to manually add it rather than having Twitch or whatever add it.

![image](https://user-images.githubusercontent.com/25333107/72872677-de8d2680-3d28-11ea-8376-faf8eb905a8f.png)
