### ISSUE TITLE
Background setting resets on login.

### ISSUE THREAD

**Issue by Rngesusxd** [Xruptor/LagBar#3]
Show the background option is ticked but background is not visible. When i untick and tick again it goes back to normal but when i relog it is not working.
I attached a screenshot for you lagbar is at bottom left corner.

![Screenshot_1](https://user-images.githubusercontent.com/70589779/91866349-183ced00-ec7b-11ea-9607-aa5a43e3c21a.png)

**Comment by Xruptor** [comment]
That should not be happening.  I'll take a look at the code.  The setting should stay put.
