### ISSUE TITLE
pre-patch errors - 1x LagBar\config.lua:68: attempt to call method 'SetBackdrop' (a nil value)

### ISSUE THREAD

**Issue by zmoose** [Xruptor/LagBar#4]
1x LagBar\config.lua:68: attempt to call method 'SetBackdrop' (a nil value)
[string "@LagBar\config.lua"]:68: in function <LagBar\config.lua:50>
[string "@LagBar\config.lua"]:181: in function <LagBar\config.lua:142>
[string "=(tail call)"]: ?

Locals:
parentFrame = LagBarAboutPanel {
 0 = <userdata>
 cancel = <function> defined @FrameXML\InterfaceOptionsFrame.lua:615
 refresh = <function> defined @FrameXML\InterfaceOptionsFrame.lua:617
 default = <function> defined @FrameXML\InterfaceOptionsFrame.lua:616
 btnReset = LagBar_config_button_1 {
 }
 name = "LagBar"
 btnBG = LagBar_config_chkbtn_1 {
 }
 okay = <function> defined @FrameXML\InterfaceOptionsFrame.lua:614
 CheckButton = LagBar_config_chkbtn_1 {
 }
}
displayText = "LagBar Frame Scale"
minVal = 0.100000
maxVal = 200
SliderBackdrop = <table> {
 bgFile = "Buttons\UI-SliderBar-Background"
 tileSize = 8
 edgeFile = "Buttons\UI-SliderBar-Border"
 tile = true
 edgeSize = 8
 insets = <table> {
 }
}
slider = LagBar_config_slider_1 {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = LagBar_config_slider_1 {
 0 = <userdata>
}
(*temporary) = <table> {
 bgFile = "Buttons\UI-SliderBar-Background"
 tileSize = 8
 edgeFile = "Buttons\UI-SliderBar-Border"
 tile = true
 edgeSize = 8
 insets = <table> {
 }
}
(*temporary) = "attempt to call method 'SetBackdrop' (a nil value)"
sliderIndex = 1
ADDON_NAME = "LagBar"

**Comment by zmoose** [comment]
1x LagBar\LagBar-4.7.lua:197: attempt to call method 'SetBackdrop' (a nil value)
[string "@LagBar\LagBar-4.7.lua"]:197: in function `DrawGUI'
[string "@LagBar\LagBar-4.7.lua"]:117: in function <LagBar\LagBar.lua:106>
[string "=(tail call)"]: ?

Locals:
self = LagBar {
 0 = <userdata>
 DrawGUI = <function> defined @LagBar\LagBar.lua:178
 configEvent = LagBar_config_eventFrame {
 }
 RestoreLayout = <function> defined @LagBar\LagBar.lua:341
 PLAYER_LOGIN = <function> defined @LagBar\LagBar.lua:106
 GetTipAnchor = <function> defined @LagBar\LagBar.lua:381
 SaveLayout = <function> defined @LagBar\LagBar.lua:316
 BackgroundToggle = <function> defined @LagBar\LagBar.lua:362
}
(*temporary) = nil
(*temporary) = LagBar {
 0 = <userdata>
 DrawGUI = <function> defined @LagBar\LagBar.lua:178
 configEvent = LagBar_config_eventFrame {
 }
 RestoreLayout = <function> defined @LagBar\LagBar.lua:341
 PLAYER_LOGIN = <function> defined @LagBar\LagBar.lua:106
 GetTipAnchor = <function> defined @LagBar\LagBar.lua:381
 SaveLayout = <function> defined @LagBar\LagBar.lua:316
 BackgroundToggle = <function> defined @LagBar\LagBar.lua:362
}
(*temporary) = nil
(*temporary) = "attempt to call method 'SetBackdrop' (a nil value)"
addon = LagBar {
 0 = <userdata>
 DrawGUI = <function> defined @LagBar\LagBar.lua:178
 configEvent = LagBar_config_eventFrame {
 }
 RestoreLayout = <function> defined @LagBar\LagBar.lua:341
 PLAYER_LOGIN = <function> defined @LagBar\LagBar.lua:106
 GetTipAnchor = <function> defined @LagBar\LagBar.lua:381
 SaveLayout = <function> defined @LagBar\LagBar.lua:316
 BackgroundToggle = <function> defined @LagBar\LagBar.lua:362
}
ADDON_NAME = "LagBar"
UPDATE_INTERVAL = 0
MAX_INTERVAL = 1
L = <table> {
 SlashScaleText = "LagBar Frame Scale"
 SlashScaleSet = "LagBar: scale has been set to [|cFF20ff20%s|r]"
 SlashFPSChkBtn = "Show the fps display."
 SlashBG = "bg"
 TooltipDragInfo = "[Hold Shift and Drag to move window.]"
 SlashResetInfo = "Reset frame position."
 SlashResetAlert = "LagBar: Frame position has been reset!"
 SlashHomePing = "homeping"
 SlashImpDisplayOn = "LagBar: Improved Ping Display is now [|cFF99CC33ON|r]"
 SlashImpDisplayChkBtn = "Show the improved ping display."
 SlashWorldPingOn = "LagBar: WorldPing is now [|cFF99CC33ON|r]"
 SlashFPSInfo = "Toggles fps display (|cFF99CC33ON/OFF|r)."
 SlashScale = "scale"
 SlashFPSOff = "LagBar: FPS is now [|cFF99CC33OFF|r]"
 SlashBGOff = "LagBar: Background is now [|cFF99CC33HIDDEN|r]"
 SlashFPS = "fps"
 SlashImpDisplay = "impdisplay"
 SlashScaleSetInvalid = "LagBar: scale invalid or number cannot be greater than 2"
 SlashHomePingOff = "LagBar: HomePing is now [|cFF99CC33OFF|r]"
 SlashHomePingOn = "LagBar: HomePing is now [|cFF99CC33ON|r]"
 SlashReset = "reset"
 Home = "H"
 SlashWorldPingOff = "LagBar: WorldPing is now [|cFF99CC33OFF|r]"
 SlashFPSOn = "LagBar: FPS is now [|cFF99CC33ON|r]"
 SlashScaleInfo = "Set the scale of the LagBar frame (0-200)"
 SlashWorldPing = "worldping"
 FPS = "fps"
 World = "W"
 SlashImpDisplayInfo = "Toggles improved ping display (|cFF99CC33ON/OFF|r)."
 Milliseconds = "ms"
 SlashBGOn = "LagBar: Background is now [|cFF99CC33SHOWN|r]"
 SlashHomePingChkBtn = "Show the home ping display."
 SlashImpDisplayOff = "LagBar: Improved Ping Display is now [|cFF99CC33OFF|r]"
 SlashWorldPingInfo = "Toggles world ping display (|cFF99CC33ON/OFF|r)."
 SlashWorldPingChkBtn = "Show the world ping display."
 SlashHomePingInfo = "Toggles home ping display (|cFF99CC33ON/OFF|r)."
 SlashBGInfo = "Show the window background."
}
LagBar_GetThresholdHexColor = <function> defined @LagBar\LagBar.lua:96

**Comment by Xruptor** [comment]
Thank you! I'll take a look into it.
