### ISSUE TITLE
Positioning per character

### ISSUE THREAD

**Issue by toobswoo** [Xruptor/LagBar#7]
Not an issue, but a request.

Is it possible for the bar to have a different position per character?

**Comment by Xruptor** [comment]
You can do this manually.

Open up the LagBar.toc file in NotePad or any simple text editor (not Microsoft Word).

Change

`## SavedVariables: LagBar_DB`

to

`## SavedVariablesPerCharacter: LagBar_DB`

The only issue will be that each time there is a LagBar update, you will have to modify the Toc file again.  This is a universal change to the addon and if I were to add it, it would force everyone to use the positioning per character.  Which I don't really want to do at the moment, but it's simple enough that you can modify it on your own.  If you need anymore help or have questions, feel free to ask! I'm here to help.
